# Generated by Django 4.2.4 on 2023-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_room_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("words", models.TextField()),
                ("difficulty", models.CharField(max_length=20)),
                ("score", models.IntegerField()),
            ],
        ),
    ]
